# This is a config for E2B sandbox template.
# You can use template ID (pwzlc59upuhljra8ic7p) or template name (whis-nextjs-text-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("whis-nextjs-text-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("whis-nextjs-text-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('whis-nextjs-text-2')

team_id = "573726eb-3d75-4e7f-bb5e-713d5ee81ec3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "whis-nextjs-text-2"
template_id = "pwzlc59upuhljra8ic7p"
